custom = {}

custom['arret'] = [{}]
custom['arret'][0]['nav'] = " - message - "
custom['arret'][0]['txt'] = ["",""]
custom['arret'][0]['txt'][0] = "arret"
custom['arret'][0]['txt'][1] = "en cours"
custom['arret'][0]['command'] = {}
custom['arret'][0]['command']["cmd"] = "sudo shutdown -h now"
custom['arret'][0]['exit'] = True

custom['ping'] = [{},{},{}]
custom['ping'][0]['nav'] = " - message - "
custom['ping'][0]['txt'] = ["",""]
custom['ping'][0]['txt'][0] = "ping box"
custom['ping'][0]['txt'][1] = "en cours"
custom['ping'][0]['command'] = {}
custom['ping'][0]['command']["cmd"] = "ping 192.168.1.1 -c 1 | grep loss | awk '{printf $4}'"
custom['ping'][0]['command']["result"] = {"0":2,"1":1}
custom['ping'][0]['goto'] = 2
custom['ping'][1]['nav'] = " - message - "
custom['ping'][1]['txt'] = ["",""]
custom['ping'][1]['txt'][0] = "ping box"
custom['ping'][1]['txt'][1] = "ok"
custom['ping'][1]['wait'] = 3
custom['ping'][1]['exit'] = True
custom['ping'][2]['nav'] = " - message - "
custom['ping'][2]['txt'] = ["",""]
custom['ping'][2]['txt'][0] = "ping box"
custom['ping'][2]['txt'][1] = "erreur"
custom['ping'][2]['wait'] = 3
custom['ping'][2]['exit'] = True

custom['restoredrive'] = [{},{},{},{}]
custom['restoredrive'][0]['nav'] = " - message - "
custom['restoredrive'][0]['txt'] = ["",""]
custom['restoredrive'][0]['txt'][0] = "compilation driver"
custom['restoredrive'][0]['txt'][1] = "0%"
custom['restoredrive'][0]['command'] = {}
custom['restoredrive'][0]['command']["cmd"] = "sudo dkms add ."
custom['restoredrive'][0]['command']["cwd"] = "/home/vampilab/drivers/rtl8192eu-linux-driver/"
custom['restoredrive'][0]['goto'] = 1
custom['restoredrive'][1]['nav'] = " - message - "
custom['restoredrive'][1]['txt'] = ["",""]
custom['restoredrive'][1]['txt'][0] = "compilation driver"
custom['restoredrive'][1]['txt'][1] = "50%"
custom['restoredrive'][1]['command'] = {}
custom['restoredrive'][1]['command']["cmd"] = "sudo dkms install rtl8192eu/1.0"
custom['restoredrive'][1]['command']["cwd"] = "/home/vampilab/drivers/rtl8192eu-linux-driver/"
custom['restoredrive'][1]['goto'] = 2
custom['restoredrive'][2]['nav'] = " - message - "
custom['restoredrive'][2]['txt'] = ["",""]
custom['restoredrive'][2]['txt'][0] = "compilation driver"
custom['restoredrive'][2]['txt'][1] = "100%"
custom['restoredrive'][2]['wait'] = 3
custom['restoredrive'][2]['goto'] = 3
custom['restoredrive'][3]['nav'] = " - message - "
custom['restoredrive'][3]['txt'] = ["",""]
custom['restoredrive'][3]['txt'][0] = "reboot"
custom['restoredrive'][3]['txt'][1] = "en cours"
custom['restoredrive'][3]['command'] = {}
custom['restoredrive'][3]['command']["cmd"] = "sudo reboot"
custom['restoredrive'][3]['exit'] = True

custom['repare'] = [{}]
custom['repare'][0]['nav'] = " - message - "
custom['repare'][0]['txt'] = ["",""]
custom['repare'][0]['txt'][0] = "reparation"
custom['repare'][0]['txt'][1] = "en cours"
custom['repare'][0]['command'] = {}
custom['repare'][0]['command']["cmd"] = "sudo shutdown -rF now"
custom['repare'][0]['exit'] = True

custom['redemarrage'] = [{}]
custom['redemarrage'][0]['nav'] = " - message - "
custom['redemarrage'][0]['txt'] = ["",""]
custom['redemarrage'][0]['txt'][0] = "redemarrage"
custom['redemarrage'][0]['txt'][1] = "en cours"
custom['redemarrage'][0]['command'] = {}
custom['redemarrage'][0]['command']["cmd"] = "sudo reboot"
custom['redemarrage'][0]['exit'] = True
